### ISSUE TITLE
Private video can't be downloaded

### ISSUE THREAD

**Issue by BeiningWu** [robincourant/the-exceptional-trajectories#2]
When i try to download the source clips, i found there're some  private videos in the dataset and i don't konw deal with it.How can I download them? 
![image](https://github.com/user-attachments/assets/db1d278e-68ec-4d0c-821a-bb1d13707e70)

**Comment by robincourant** [comment]
Hi,
Sorry, but this issue is related to CondensedMovies, so I can't help you with it. I noticed you have opened an issue on their repo; I hope they respond quickly.
